# Generated by Django 5.2 on 2025-05-07 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0026_alter_paymenttype_name_alter_sales_payment_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='cashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_amount', models.FloatField(default=0)),
                ('opening_date', models.FloatField(default=0)),
                ('close_date', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CashRegisterSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.cashregister')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.sales')),
            ],
            options={
                'unique_together': {('cash_register', 'sale')},
            },
        ),
        migrations.AddField(
            model_name='cashregister',
            name='sales',
            field=models.ManyToManyField(through='posApp.CashRegisterSales', to='posApp.sales'),
        ),
    ]
