# Generated by Django 5.2 on 2025-05-07 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0028_cashregister_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='opening_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
