# Generated by Django 5.2 on 2025-05-09 03:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0029_alter_cashregister_close_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.cashregister')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cash_registers', models.ManyToManyField(through='posApp.CashRegisterExpense', to='posApp.cashregister')),
            ],
        ),
        migrations.AddField(
            model_name='cashregisterexpense',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.expense'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='expenses',
            field=models.ManyToManyField(through='posApp.CashRegisterExpense', to='posApp.expense'),
        ),
        migrations.AlterUniqueTogether(
            name='cashregisterexpense',
            unique_together={('cash_register', 'expense')},
        ),
    ]
