# Generated by Django 5.2 on 2025-05-09 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0030_cashregisterexpense_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='cash_registers',
        ),


#        migrations.CreateModel(
 #           name='Expense',
  #          fields=[
   #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
   #             ('description', models.CharField(max_length=255)),
   #             ('amount', models.FloatField()),
   #             ('expense_date', models.DateTimeField(default=django.utils.timezone.now)),
   #             ('cash_register', models.ForeignKey(
   #                 to='posApp.cashRegister',  
   #                 on_delete=models.CASCADE,
   #                 related_name='expenses',  
   #             )),            ],
  #      ),
        
        migrations.AddField(
            model_name='expense',
            name='cash_register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='posApp.cashregister'),
        ),
        migrations.DeleteModel(
            name='CashRegisterExpense',
        ),
    ]
