# Generated by Django 5.2 on 2025-05-17 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0031_remove_cashregister_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='payment_type_id',
        ),
        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='posApp.paymenttype')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_payments', to='posApp.sales')),
            ],
        ),
    ]
