# Generated by Django 5.2 on 2025-05-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0032_remove_sales_payment_type_id_salespayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='opening_amount',
        ),
    ]
