# Generated by Django 5.2.1 on 2025-06-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0033_remove_cashregister_opening_amount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cashregistersales',
            index=models.Index(fields=['cash_register'], name='posApp_cash_cash_re_b79b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashregistersales',
            index=models.Index(fields=['sale'], name='posApp_cash_sale_id_e5b4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['date_added'], name='posApp_sale_date_ad_b4f79b_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitems',
            index=models.Index(fields=['sale_id'], name='posApp_sale_sale_id_91f873_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitems',
            index=models.Index(fields=['product_id'], name='posApp_sale_product_86e67b_idx'),
        ),
        migrations.AddIndex(
            model_name='salespayment',
            index=models.Index(fields=['sale'], name='posApp_sale_sale_id_fd707c_idx'),
        ),
        migrations.AddIndex(
            model_name='salespayment',
            index=models.Index(fields=['payment_type'], name='posApp_sale_payment_7a81f7_idx'),
        ),
    ]
