# Generated by Django 5.2.1 on 2025-08-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0034_cashregistersales_posapp_cash_cash_re_b79b5f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
