# Generated by Django 5.2.1 on 2025-08-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0035_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='code',
        ),
    ]
